[package]
name = "sal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
csv = "1.3.1"
json = "0.12.4"
ratatui = "0.29.0"
rusqlite = { version = "0.33.0", features = ["bundled", "chrono"] }
tui-input = "0.11.1"
